version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - anb_postgres_data:/var/lib/postgresql/data

  api:
    build: ..
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  anb_postgres_data:
