services:
  rabbitmq:
    image: rabbitmq:4.1.4-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:15672/api/healthchecks/node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  rabbitmq-lib:
  rabbitmq-log:
