services:
  rabbitmq:
    image: rabbitmq:4.1.4-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: "10s"
      timeout: "3s"
      retries: 3
      start_period: "10s"

volumes:
  rabbitmq-lib:
  rabbitmq-log:
