name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=sqlite:///./test.db" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r app-worker/requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests with coverage
        run: |
          export PYTHONPATH=.:app-worker
          pytest tests/ -v --cov=app --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd docker
          docker compose build api

  sonar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for coverage
        run: |
          pip install -r requirements.txt
          pip install -r app-worker/requirements.txt
          pip install pytest pytest-cov

      - name: Generate coverage report and fix paths
        run: |
          export PYTHONPATH=.:app-worker:shared
          
          # Primero genera el reporte normal
          pytest tests/ -v --cov=app --cov=app-worker --cov=shared --cov-report=xml --cov-report=html
          
          # Luego repara las rutas en el coverage.xml
          python -c "
          import xml.etree.ElementTree as ET
          import os
          
          # Parsear el XML
          tree = ET.parse('coverage.xml')
          root = tree.getroot()
          
          # Remover todas las fuentes existentes
          sources = root.find('sources')
          if sources is not None:
              root.remove(sources)
          
          # Agregar solo fuente relativa
          new_sources = ET.SubElement(root, 'sources')
          ET.SubElement(new_sources, 'source').text = '.'
          
          # Reparar las rutas en los packages
          for package in root.findall('.//package'):
              for cls in package.findall('.//class'):
                  filename = cls.get('filename')
                  if filename and filename.startswith('/home/runner/work/'):
                      # Extraer solo la parte relativa del path
                      relative_path = filename.split('/ANB-Rising-Stars-Showcase/')[-1]
                      cls.set('filename', relative_path)
          
          # Guardar el archivo reparado
          tree.write('coverage.xml', encoding='utf-8', xml_declaration=True)
          "
          
          echo "=== Coverage.xml reparado ==="
          head -25 coverage.xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL || 'https://sonarcloud.io' }}
        with:
          args: >
            -Dsonar.projectKey=leonelparrales22_ANB-Rising-Stars-Showcase
            -Dsonar.organization=leonelparrales22
            -Dsonar.sources=app,app-worker,shared
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.coverage.plugin=pytest
            -Dsonar.python.version=3.11
            -Dsonar.coverage.exclusions=tests/**,**/__pycache__/**,**/*.pyc,venv/**,env/**
            -Dsonar.branch.name=${{ github.ref_name }}